### ISSUE TITLE
Fails to compile with latest lipgloss version

### ISSUE THREAD

**Issue by Lilith-Cyber** [elewis787/boa#18]
### Issue
Library is installed as recommended in the readme `go get -u github.com/elewis787/boa` but it fails to compile as the newest lipgloss version had a breaking change [related commit in lipgloss](https://github.com/charmbracelet/lipgloss/commit/b9c2626fe71863967282a96487018827117c305f#diff-2339bd54dfd9fc2ac2d3f9ad6d27926563eef8483c06cd0651d38d6e4127917aR167)
### Error
```
# github.com/elewis787/boa
C:\Users\Lilith\go\pkg\mod\github.com\elewis787\boa@v0.1.1\cmdlist.go:41:8: cannot use func(s string) string {…} (value of type func(s string) string) as func(strs ...string) string value in assignment
```
### Versions
Go: 1.20.5
Lipgloss: 0.7.1
Boa: 0.1.1

**Comment by Lilith-Cyber** [comment]
Should be fixed with my [pull request](https://github.com/elewis787/boa/pull/19)

**Comment by elewis787** [comment]
Thank you - I will be reviewing this today.

**Comment by elewis787** [comment]
sorry for the delay! Merged - thank you!
