### ISSUE TITLE
Make `AltScreen` is an option

### ISSUE THREAD

**Issue by abdfnx** [elewis787/boa#4]
Hi @elewis787, Nice project

Can you make the `AltScreen` is an option ?

like this format

```go
boa.WithAltScreen(false) // or true
```

**Comment by elewis787** [comment]
@abdfnx absolutely! I am planning on improving some of the optional configurations and will add this to that effort.

**Comment by elewis787** [comment]
Changes have been added to v0.1.0 

I realized after pushing that the readme and go docs could use some updates so I will be circling back to that next but here is an example usage 

```
	styles := boa.DefaultStyles()
	styles.Title.BorderForeground(lipgloss.AdaptiveColor{Light: `#E3BD2D`, Dark: `#E3BD2D`})
	styles.Border.BorderForeground(lipgloss.AdaptiveColor{Light: `#E3BD2D`, Dark: `#E3BD2D`})
	styles.SelectedItem.Foreground(lipgloss.AdaptiveColor{Light: `#353C3B`, Dark: `#353C3B`}).
		Background(lipgloss.AdaptiveColor{Light: `#E3BD2D`, Dark: `#E3BD2D`})
	b := boa.New(boa.WithAltScreen(true), boa.WithStyles(styles))
	
	rootCmd.SetHelpFunc(b.HelpFunc)
	rootCmd.SetUsageFunc(b.UsageFunc)
	
``` 

You can still use the package level HelpFunc and UsageFunc if you do not want to change any of the default behavior 

i.e 
```
rootCmd.SetHelpFunc(boa.HelpFunc)
rootCmd.SetUsageFunc(boa.UsageFunc)
```

Closing this out but please feel free to reopen if this does not solve the issue !

**Comment by abdfnx** [comment]
thank you so much @elewis787
