### ISSUE TITLE
Cannot use a Long on a sub command

### ISSUE THREAD

**Issue by corinnesollows** [elewis787/boa#7]
Cannot use a Long on a sub command. There is a check that if it is not the root that the Long field is never displayed.
The subcommand list uses the Short, but when you enter into a subcommand's help menu the Description is also using the Short so you cannot give further information

**Comment by elewis787** [comment]
Good catch - I will work on getting this resolved.

**Comment by elewis787** [comment]
fixed in v0.1.1
